### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by hopkin-lai** [minqukanq/hierarchical-multi-label-text-classification#1]
When I tried to run the code in Linux command, it occured:
IndexError: index out of range in self
```Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main()
  File "train.py", line 233, in main
    train(args)
  File "train.py", line 87, in train
    _, outputs = net(x_train)
  File "/opt/conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/laihuapeng01/hierarchical-multi-label-text-classification/models/harnn.py", line 70, in forward
    embedded_sentence = self.embedding(input_x)
  File "/opt/conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
```
Can u explain what problem it is ? THX first!

**Comment by minqukanq** [comment]
There seems to be a problem in the process of creating the vocab.

Are the data entered when creating the vocab and the data entered into the model the same data set?

**Comment by hopkin-lai** [comment]
> 

yeah, I just simply run the source code, and the data set is the same data set "train_sample.json"

**Comment by minqukanq** [comment]
I'll check again. I'll be back soon.

**Comment by minqukanq** [comment]
I checked the error. I'll fix it soon.
thank you.

**Comment by hopkin-lai** [comment]
> 

Haha, u r so welcome. By the way, another error ocuuerd not long age:
```
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main()
  File "train.py", line 233, in main
    train(args)
  File "train.py", line 88, in train
    loss = criterion(outputs[0], outputs[1], outputs[2], outputs[3], outputs[4],outputs[5],outputs[6],
  File "/opt/conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 11 positional arguments but 13 were given
```
I am totally new to this field.

**Comment by minqukanq** [comment]
Fixed the last mentioned error.

Remove 'outputs[5],outputs[6]' or add parameter on Loss class
Thank you

[last errorhttps://github.com/minqukanq/hierarchical-multi-label-text-classification/commit/30a20c7a94d34c922b65249c4c4ed91908253078](https://github.com/minqukanq/hierarchical-multi-label-text-classification/commit/30a20c7a94d34c922b65249c4c4ed91908253078)

**Comment by minqukanq** [comment]
The first mentioned error is currently being fixed, but you can fix it first.

The vocab_size to be passed as a parameter of the model must pass the vocab_size of the entire data set, not the vocab_size of the traindataset.

**Comment by minqukanq** [comment]
Fixed. Thank you

**Comment by minqukanq** [comment]
If you have faced with new error, please make new issue.

Thank you
